language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install

before_script:

script:
  # basic tests - command line tool installed and gives help/usage
  - ./sparkyRecipValidate.py -h
  # fuller test - runs with specified file, with various input / output cases
  - ./sparkyRecipValidate.py <valtest.csv >results.csv
  - ./sparkyRecipValidate.py -i valtest.csv -o results2.csv
  - cat valtest.csv | ./sparkyRecipValidate.py > results2.csv

branches:
  only:
    - master